### ISSUE TITLE
Set first root item as expendable by default

### ISSUE THREAD

**Issue by mladenbabic** [muditsen/multilevelrecyclerview#3]
I implemented your lib and I think that is great, but I have one issue which bugs me. I want to show expandable list but with the first row as expandable. I have tried to set on Item.setExpanded(true), but in that case, it throws me an error:

`  java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.remove(ArrayList.java:503)
  at com.multilevelview.MultiLevelRecyclerView.removePrevItems(MultiLevelRecyclerView.java:177)
 at com..multilevelview.MultiLevelRecyclerView.onItemClick(MultiLevelRecyclerView.java:159)`

Any idea what could be a problem?

**Comment by vankhoa01** [comment]
Do you have been fixed this issue @mladenbabic ?

**Comment by muditsenJabong** [comment]
Yes..!!!
